add support for matching with `HasPrefix` to `FilteredRelayConfig`
returntocorp/semgrep-network-broker pull request #36
Opened 2023-08-22 18:22 UTC by milo-minderbinder

This change adds a new `HasPrefix` field to the `FilteredRelayConfig`, which allows a relay endpoint to match & forward a request only if the value at the given JSON path in the request's body starts with at least one of the configured strings defined by the `HasPrefix` rule.

This allows users to create relay configurations which, for example, will only forward requests with a comment body that starts with "/semgrep", while dropping/ignoring requests with a comment body that merely _contains_ "/semgrep" (for example if someone is quoting an earlier comment in the review thread, or instructing on how to use the feature).

2023-08-22 18:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/returntocorp/semgrep-network-broker?pullRequest=36) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/returntocorp/semgrep-network-broker?pullRequest=36) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/returntocorp/semgrep-network-broker?pullRequest=36) it.</sub>

2023-08-28 22:56 UTC, sinat101 requested changes, later dismissed

2023-08-28 22:56 UTC, sinat101 commented on examples/github-pr-comment-relay.yaml
> +      # - "/semgrep ignore"
I'm not sure how practical this example is, in what scenario would we want to allow someone to ignore findings but not re-open already ignored ones?

That aside, I also feel like this might confuse a novice/first-time user of the relay functionality. Perhaps we can replace this comment with one explaining what `hasPrefix` is doing.

2023-08-28 22:56 UTC, sinat101 commented on examples/github-pr-comment-relay.yaml
> +      # - "/semgrep ignore"
```suggestion
      # Here, we use `hasPrefix` to ensure only PR comments beginning with "/semgrep"
      # are relayed to the webhook destination.
      hasPrefix:
      - "/semgrep"
```

2023-08-29 13:42 UTC, tpetr commented on examples/github-pr-comment-relay.yaml
> +      # - "/semgrep ignore"
Agreed, let's keep it simple. It's an interesting detail, though -- maybe we can move it to the README.

2023-08-29 13:43 UTC, tpetr approved these changes
LGTM, thanks! And apologies for the delay in review -- I updated the CODEOWNERS so that I'll get automatically flagged as a reviewer next time.

2023-08-29 13:44 UTC, merged